// H1, acceptance test A2: HARM's proposition semantics against an independent oracle (iverilog).
// For each expression the fixture has two columns computed by iverilog:
//   SV         the SystemVerilog value (0, 1, x, z)
//   HARM model the SV value with every relational/equality comparison made false when an operand
//              contains x/z: HARM's documented semantics, unchanged by H1 (DECISIONS.md, D-011)
// A proposition must hold exactly where the HARM model is 1. Rows where SV and the model differ
// are counted and reported (they are the known x/z semantic gap), not failed.
// The fixture is generated by tests/oracle/gen_iverilog_fixture.py.
#include <gtest/gtest-message.h>
#include <gtest/gtest-test-part.h>

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "CSVtraceReader.hh"
#include "Trace.hh"
#include "TraceReader.hh"
#include "formula/atom/Atom.hh"
#include "propositionParsingUtils.hh"
#include "gtest/gtest_pred_impl.h"

using namespace harm;
using namespace expression;

namespace {

const std::string fixtureDir = "../tests/oracle/fixture/";

struct OracleCase {
  std::string category;
  std::string sv;    // one char per row: 0, 1, x or z
  std::string model; // HARM's documented semantics, one char per row
  std::string expr;
};

std::vector<OracleCase> readCases() {
  std::vector<OracleCase> cases;
  std::ifstream in(fixtureDir + "cases.txt");
  std::string line;
  while (std::getline(in, line)) {
    size_t p1 = line.find('|');
    size_t p2 = line.find('|', p1 + 1);
    size_t p3 = line.find('|', p2 + 1);
    cases.push_back({line.substr(0, p1),
                     line.substr(p1 + 1, p2 - p1 - 1),
                     line.substr(p2 + 1, p3 - p2 - 1),
                     line.substr(p3 + 1)});
  }
  return cases;
}

struct Outcome {
  size_t cases = 0, parseErrors = 0, mismatching = 0;
  size_t svGap = 0; // cases where SV and the HARM model differ on some row
  std::vector<std::string> report;
};

Outcome check(const std::string &category) {
  TraceReader *tr = new CSVtraceReader(fixtureDir + "trace.csv");
  const TracePtr &trace = tr->readTrace();
  Outcome o;
  for (const auto &c : readCases()) {
    if (c.category != category) {
      continue;
    }
    o.cases++;
    std::string error;
    PropositionPtr p = hparser::tryParseProposition(c.expr, trace, error);
    if (p == nullptr) {
      o.parseErrors++;
      if (o.report.size() < 15) {
        o.report.push_back("PARSE  " + c.expr + "\n       " + error);
      }
      continue;
    }
    std::string got;
    bool differs = false;
    for (size_t t = 0; t < c.model.size(); t++) {
      bool holds = p->evaluate(t);
      got += holds ? '1' : '0';
      differs |= holds != (c.model[t] == '1');
    }
    if (c.sv != c.model) {
      o.svGap++;
    }
    if (differs) {
      o.mismatching++;
      if (o.report.size() < 15) {
        o.report.push_back("VALUE  " + c.expr + "\n       SV:    " +
                           c.sv + "\n       model: " + c.model +
                           "\n       HARM:  " + got);
      }
    }
  }
  delete tr;
  return o;
}

void print(const std::string &category, const Outcome &o) {
  std::cout << "[" << category << "] cases: " << o.cases
            << ", parse errors: " << o.parseErrors
            << ", value mismatches: " << o.mismatching
            << ", cases where SV differs from HARM's model (x/z gap): "
            << o.svGap << "\n";
  for (const auto &r : o.report) {
    std::cout << r << "\n";
  }
}

} // namespace

TEST(PropositionOracleTest, newFeaturesMatchModel) {
  Outcome o = check("new");
  print("new", o);
  ASSERT_GT(o.cases, 0u);
  ASSERT_EQ(o.parseErrors, 0u);
  ASSERT_EQ(o.mismatching, 0u);
}

TEST(PropositionOracleTest, existingSyntaxMatchesModel) {
  Outcome o = check("existing");
  print("existing", o);
  ASSERT_GT(o.cases, 0u);
  ASSERT_EQ(o.parseErrors, 0u);
  ASSERT_EQ(o.mismatching, 0u);
}
