#install third_party libraries
file(COPY ${S} DESTINATION ${IP}/harm/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${B} DESTINATION ${IP}/harm/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${A} DESTINATION ${IP}/harm/lib FOLLOW_SYMLINK_CHAIN)
file(COPY ${Z} DESTINATION ${IP}/harm/lib FOLLOW_SYMLINK_CHAIN)
